name: lint-test

on:
  pull_request:

permissions: read-all

concurrency:
  group: lint-test-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint-test:
    name: lint-test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Actions Toolbox
        uses: wallentx/gh-actions/composite/actions-toolbox@main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          checkout: false
          include-packages: |
            shellcheck

      - name: Run lint-test
        run: .github/scripts/lint-test
